/**
 * # ============================================================
 * # Grafana Cloud 集成 (Cycle 54 G54-03)
 * # ============================================================
 * # 核心作用：Grafana 仪表盘 + Datasource + Provisioning 集成
 * # 支持：Grafana HTTP API + Provisioning YAML/JSON 生成 + Cloud 接入
 * # ====================================
 * # 修改记录：
 * #   - 2026-08-01 | v1.0.0 | Cycle 54 G54-03 初次创建
 * # ====================================
 */

import type {
  ClientConfig,
  HealthCheckResult,
  PlatformEndpoint,
  PlatformEvent,
  PlatformEventListener,
  PlatformExportResult,
} from './platformTypes';
import { DEFAULT_RETRY_POLICY } from './platformTypes';
import { httpRequest, httpRequestWithRetry, buildUrl, delay } from './httpClient';

/** Grafana 数据源类型 */
export type GrafanaDatasourceType =
  | 'prometheus'
  | 'loki'
  | 'tempo'
  | 'jaeger'
  | 'elasticsearch'
  | 'influxdb'
  | 'mysql'
  | 'postgres'
  | 'graphite'
  | 'cloudwatch'
  | 'stackdriver'
  | 'azuremonitor'
  | 'testdata';

/** Grafana Datasource 配置 */
export interface GrafanaDatasource {
  name: string;
  type: GrafanaDatasourceType;
  uid?: string;
  access: 'proxy' | 'direct';
  url: string;
  user?: string;
  database?: string;
  basicAuth?: boolean;
  basicAuthUser?: string;
  isDefault?: boolean;
  jsonData?: Record<string, unknown>;
  secureJsonData?: Record<string, string>;
  readOnly?: boolean;
  withCredentials?: boolean;
  version?: number;
}

/** Grafana Folder 配置 */
export interface GrafanaFolder {
  uid: string;
  title: string;
  description?: string;
  parentUid?: string;
}

/** Grafana Dashboard 上传响应 */
export interface GrafanaDashboardUploadResponse {
  id: number;
  uid: string;
  url: string;
  status: 'success' | 'failure';
  version: number;
  slug?: string;
}

/** Grafana API 响应包装 */
export interface GrafanaApiResponse<T = unknown> {
  status: number;
  data: T;
  durationMs: number;
  message?: string;
}

export interface GrafanaClientConfig extends ClientConfig {
  /** 默认 Folder UID */
  defaultFolderUid?: string;
  /** Org ID（默认 1） */
  orgId?: number;
}

/**
 * 转换 Datasource 为 Grafana API 格式
 */
export function toGrafanaDatasourcePayload(ds: GrafanaDatasource): Record<string, unknown> {
  const payload: Record<string, unknown> = {
    name: ds.name,
    type: ds.type,
    access: ds.access,
    url: ds.url,
    basicAuth: ds.basicAuth ?? false,
    basicAuthUser: ds.basicAuthUser,
    isDefault: ds.isDefault ?? false,
    readOnly: ds.readOnly ?? false,
    withCredentials: ds.withCredentials ?? false,
    jsonData: ds.jsonData ?? {},
    secureJsonData: ds.secureJsonData ?? {},
  };
  if (ds.uid) payload.uid = ds.uid;
  if (ds.user) payload.user = ds.user;
  if (ds.database) payload.database = ds.database;
  return payload;
}

/**
 * 生成 Datasource Provisioning YAML
 * 符合 Grafana 官方 provisioning 规范
 */
export function generateDatasourceProvisioningYaml(
  apiKey: string,
  datasources: GrafanaDatasource[]
): string {
  const lines: string[] = [];
  lines.push('# Grafana Datasource Provisioning');
  lines.push('# Generated by Hermes Observability Platform');
  lines.push('# Generated at: ' + new Date().toISOString());
  lines.push('');
  lines.push('apiVersion: 1');
  lines.push('');
  lines.push('deleteDatasources:');
  lines.push('  - name: hermes-mock-*');
  lines.push('    orgId: 1');
  lines.push('');
  lines.push('datasources:');
  for (const ds of datasources) {
    lines.push(`  - name: ${ds.name}`);
    lines.push(`    type: ${ds.type}`);
    if (ds.uid) lines.push(`    uid: ${ds.uid}`);
    lines.push(`    access: ${ds.access}`);
    lines.push(`    url: ${ds.url}`);
    lines.push(`    isDefault: ${ds.isDefault ?? false}`);
    lines.push(`    basicAuth: ${ds.basicAuth ?? false}`);
    if (ds.basicAuthUser) lines.push(`    basicAuthUser: ${ds.basicAuthUser}`);
    lines.push(`    editable: true`);
    if (ds.jsonData) {
      lines.push('    jsonData:');
      for (const [k, v] of Object.entries(ds.jsonData)) {
        lines.push(`      ${k}: ${JSON.stringify(v)}`);
      }
    }
    if (ds.secureJsonData) {
      lines.push('    secureJsonData:');
      for (const [k] of Object.entries(ds.secureJsonData)) {
        lines.push(`      ${k}: \${${k.toUpperCase()}}`);
      }
    }
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * 生成 Dashboard Provider Provisioning YAML
 * 用于让 Grafana 自动从文件系统加载 dashboard JSON
 */
export function generateDashboardProviderYaml(
  apiKey: string,
  options: {
    name: string;
    folder?: string;
    folderUid?: string;
    type: 'file' | 'http';
    disableDeletion?: boolean;
    updateIntervalSeconds?: number;
    allowUiUpdates?: boolean;
    options?: Record<string, unknown>;
  }
): string {
  const lines: string[] = [];
  lines.push('# Grafana Dashboard Provider');
  lines.push('apiVersion: 1');
  lines.push('');
  lines.push('providers:');
  lines.push(`  - name: '${options.name}'`);
  lines.push(`    orgId: 1`);
  lines.push(`    folder: '${options.folder ?? ''}'`);
  if (options.folderUid) lines.push(`    folderUid: '${options.folderUid}'`);
  lines.push(`    type: ${options.type}`);
  lines.push(`    disableDeletion: ${options.disableDeletion ?? false}`);
  if (options.updateIntervalSeconds !== undefined) {
    lines.push(`    updateIntervalSeconds: ${options.updateIntervalSeconds}`);
  }
  lines.push(`    allowUiUpdates: ${options.allowUiUpdates ?? true}`);
  lines.push(`    options:`);
  if (options.type === 'file') {
    lines.push(`      foldersFromFilesStructure: true`);
    lines.push(`      path: /etc/grafana/dashboards`);
  } else {
    for (const [k, v] of Object.entries(options.options ?? {})) {
      lines.push(`      ${k}: ${JSON.stringify(v)}`);
    }
  }
  return lines.join('\n');
}

/**
 * 生成 Alerting Provisioning YAML
 */
export function generateAlertingProvisioningYaml(options: {
  contactPoints: Array<{
    org: string;
    name: string;
    receivers: Array<{ type: string; settings: Record<string, unknown> }>;
  }>;
  policies: Array<{
    org: string;
    receiver: string;
    groupBy?: string[];
    groupWait?: string;
    groupInterval?: string;
    repeatInterval?: string;
    routes?: unknown[];
  }>;
}): string {
  const lines: string[] = [];
  lines.push('# Grafana Alerting Provisioning');
  lines.push('apiVersion: 1');
  lines.push('');
  lines.push('contactPoints:');
  for (const cp of options.contactPoints) {
    lines.push(`  - orgId: 1`);
    lines.push(`    name: ${cp.name}`);
    lines.push(`    receivers:`);
    for (const r of cp.receivers) {
      lines.push(`      - type: ${r.type}`);
      lines.push('        settings:');
      for (const [k, v] of Object.entries(r.settings)) {
        lines.push(`          ${k}: ${JSON.stringify(v)}`);
      }
    }
    lines.push('');
  }
  lines.push('policies:');
  for (const p of options.policies) {
    lines.push(`  - orgId: 1`);
    lines.push(`    receiver: ${p.receiver}`);
    if (p.groupBy) lines.push(`    group_by: [${p.groupBy.map((s) => `'${s}'`).join(', ')}]`);
    if (p.groupWait) lines.push(`    group_wait: ${p.groupWait}`);
    if (p.groupInterval) lines.push(`    group_interval: ${p.groupInterval}`);
    if (p.repeatInterval) lines.push(`    repeat_interval: ${p.repeatInterval}`);
  }
  return lines.join('\n');
}

/**
 * 包装 Dashboard JSON 为 Grafana 上传格式
 */
export function wrapDashboardForUpload(
  dashboard: Record<string, unknown>,
  options: { folderUid?: string; message?: string; overwrite?: boolean; dashboardId?: number } = {}
): Record<string, unknown> {
  const payload: Record<string, unknown> = {
    dashboard,
    message: options.message ?? 'Uploaded by Hermes',
    overwrite: options.overwrite ?? true,
  };
  if (options.folderUid) payload.folderUid = options.folderUid;
  if (options.dashboardId !== undefined) payload.dashboardId = options.dashboardId;
  return payload;
}

/**
 * Grafana HTTP API 客户端
 */
export class GrafanaClient {
  readonly name = 'grafana';
  private readonly config: GrafanaClientConfig;
  private readonly listeners: Set<PlatformEventListener> = new Set();
  private readonly history: PlatformExportResult[] = [];
  private running = false;

  constructor(config: GrafanaClientConfig) {
    this.config = {
      ...config,
      retryPolicy: config.retryPolicy ?? DEFAULT_RETRY_POLICY,
      enabled: config.enabled ?? true,
      orgId: config.orgId ?? 1,
    };
  }

  async start(): Promise<void> {
    this.running = true;
    this.emit({ type: 'connected', platform: this.name, timestamp: Date.now() });
  }

  async shutdown(): Promise<void> {
    this.running = false;
    this.emit({ type: 'disconnected', platform: this.name, timestamp: Date.now() });
  }

  /**
   * 上传 Dashboard
   */
  async uploadDashboard(
    dashboard: Record<string, unknown>,
    options: { folderUid?: string; message?: string; overwrite?: boolean } = {}
  ): Promise<GrafanaApiResponse<GrafanaDashboardUploadResponse>> {
    if (!this.running) {
      return { status: 0, data: {} as GrafanaDashboardUploadResponse, durationMs: 0, message: 'Not started' };
    }
    const start = Date.now();
    const url = buildUrl(this.config.endpoint.baseUrl, '/api/dashboards/db', this.config.endpoint.pathPrefix);
    const body = JSON.stringify(wrapDashboardForUpload(dashboard, { ...options, folderUid: options.folderUid ?? this.config.defaultFolderUid }));

    if (this.config.mode === 'mock') {
      await delay(20 + Math.random() * 50);
      const response: GrafanaDashboardUploadResponse = {
        id: Math.floor(Math.random() * 10000),
        uid: 'mock-' + Math.random().toString(36).slice(2, 10),
        url: `/d/mock-dashboard`,
        status: 'success',
        version: 1,
        slug: 'mock-dashboard',
      };
      const result: PlatformExportResult = {
        platform: this.name,
        successCount: 1,
        failureCount: 0,
        durationMs: Date.now() - start,
        timestamp: Date.now(),
        retries: 0,
        httpStatus: 200,
      };
      this.history.push(result);
      this.emit({ type: 'export-success', platform: this.name, timestamp: Date.now() });
      return { status: 200, data: response, durationMs: result.durationMs };
    }

    let retries = 0;
    try {
      const res = await httpRequestWithRetry(
        {
          method: 'POST',
          url,
          headers: { 'Content-Type': 'application/json', 'X-Grafana-Org-Id': String(this.config.orgId) },
          body,
          timeoutMs: this.config.endpoint.timeoutMs,
          credentials: this.config.endpoint.credentials,
        },
        this.config.retryPolicy ?? DEFAULT_RETRY_POLICY,
        (attempt) => { retries = attempt; }
      );
      const data = res.body ? JSON.parse(res.body) : {};
      return { status: res.status, data, durationMs: Date.now() - start, message: res.status >= 400 ? res.body : undefined };
    } catch (err) {
      return {
        status: 0,
        data: {} as GrafanaDashboardUploadResponse,
        durationMs: Date.now() - start,
        message: err instanceof Error ? err.message : String(err),
      };
    }
  }

  /**
   * 创建 Datasource
   */
  async createDatasource(ds: GrafanaDatasource): Promise<GrafanaApiResponse<{ id: number; uid: string; name: string }>> {
    const start = Date.now();
    if (this.config.mode === 'mock') {
      await delay(15);
      const data = { id: Math.floor(Math.random() * 100), uid: ds.uid ?? 'mock-ds', name: ds.name };
      this.history.push({ platform: this.name, successCount: 1, failureCount: 0, durationMs: Date.now() - start, timestamp: Date.now(), retries: 0, httpStatus: 200 });
      return { status: 200, data, durationMs: Date.now() - start };
    }
    const url = buildUrl(this.config.endpoint.baseUrl, '/api/datasources', this.config.endpoint.pathPrefix);
    const body = JSON.stringify(toGrafanaDatasourcePayload(ds));
    try {
      const res = await httpRequest({
        method: 'POST',
        url,
        headers: { 'Content-Type': 'application/json' },
        body,
        timeoutMs: this.config.endpoint.timeoutMs,
        credentials: this.config.endpoint.credentials,
      });
      const data = res.body ? JSON.parse(res.body) : {};
      return { status: res.status, data, durationMs: Date.now() - start, message: res.status >= 400 ? res.body : undefined };
    } catch (err) {
      return { status: 0, data: { id: 0, uid: '', name: '' }, durationMs: Date.now() - start, message: err instanceof Error ? err.message : String(err) };
    }
  }

  /**
   * 列出所有 Datasources
   */
  async listDatasources(): Promise<GrafanaApiResponse<GrafanaDatasource[]>> {
    const start = Date.now();
    if (this.config.mode === 'mock') {
      await delay(10);
      const data: GrafanaDatasource[] = [
        { name: 'Prometheus', type: 'prometheus', access: 'proxy', url: 'http://prometheus:9090' },
        { name: 'Loki', type: 'loki', access: 'proxy', url: 'http://loki:3100' },
        { name: 'Tempo', type: 'tempo', access: 'proxy', url: 'http://tempo:3200' },
      ];
      return { status: 200, data, durationMs: Date.now() - start };
    }
    const url = buildUrl(this.config.endpoint.baseUrl, '/api/datasources', this.config.endpoint.pathPrefix);
    try {
      const res = await httpRequest({
        method: 'GET',
        url,
        timeoutMs: this.config.endpoint.timeoutMs,
        credentials: this.config.endpoint.credentials,
      });
      const data = res.body ? JSON.parse(res.body) : [];
      return { status: res.status, data, durationMs: Date.now() - start };
    } catch (err) {
      return { status: 0, data: [], durationMs: Date.now() - start, message: err instanceof Error ? err.message : String(err) };
    }
  }

  /**
   * 创建 Folder
   */
  async createFolder(folder: GrafanaFolder): Promise<GrafanaApiResponse<{ id: number; uid: string; title: string }>> {
    const start = Date.now();
    if (this.config.mode === 'mock') {
      await delay(10);
      return { status: 200, data: { id: 1, uid: folder.uid, title: folder.title }, durationMs: Date.now() - start };
    }
    const url = buildUrl(this.config.endpoint.baseUrl, '/api/folders', this.config.endpoint.pathPrefix);
    try {
      const res = await httpRequest({
        method: 'POST',
        url,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(folder),
        timeoutMs: this.config.endpoint.timeoutMs,
        credentials: this.config.endpoint.credentials,
      });
      const data = res.body ? JSON.parse(res.body) : {};
      return { status: res.status, data, durationMs: Date.now() - start };
    } catch (err) {
      return { status: 0, data: { id: 0, uid: '', title: '' }, durationMs: Date.now() - start, message: err instanceof Error ? err.message : String(err) };
    }
  }

  /**
   * 健康检查
   */
  async healthCheck(): Promise<HealthCheckResult> {
    const start = Date.now();
    if (this.config.mode === 'mock' || !this.config.enabled) {
      return { platform: this.name, status: 'connected', latencyMs: 0, timestamp: Date.now(), details: { mode: 'mock' } };
    }
    try {
      const url = buildUrl(this.config.endpoint.baseUrl, '/api/health', this.config.endpoint.pathPrefix);
      const res = await httpRequest({
        method: 'GET',
        url,
        timeoutMs: this.config.endpoint.timeoutMs ?? 5000,
        credentials: this.config.endpoint.credentials,
      });
      return {
        platform: this.name,
        status: res.status === 200 ? 'connected' : 'error',
        latencyMs: Date.now() - start,
        timestamp: Date.now(),
        details: { status: res.status, body: res.body.slice(0, 200) },
      };
    } catch (err) {
      return {
        platform: this.name,
        status: 'error',
        latencyMs: Date.now() - start,
        timestamp: Date.now(),
        error: err instanceof Error ? err.message : String(err),
      };
    }
  }

  /**
   * 测试 Datasource 连接
   */
  async testDatasource(ds: GrafanaDatasource): Promise<GrafanaApiResponse<{ message: string; status: string }>> {
    const start = Date.now();
    if (this.config.mode === 'mock') {
      await delay(30);
      return { status: 200, data: { message: 'Mock test success', status: 'success' }, durationMs: Date.now() - start };
    }
    const url = buildUrl(this.config.endpoint.baseUrl, '/api/datasources/test', this.config.endpoint.pathPrefix);
    try {
      const res = await httpRequest({
        method: 'POST',
        url,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(toGrafanaDatasourcePayload(ds)),
        timeoutMs: this.config.endpoint.timeoutMs,
        credentials: this.config.endpoint.credentials,
      });
      const data = res.body ? JSON.parse(res.body) : { message: '', status: '' };
      return { status: res.status, data, durationMs: Date.now() - start };
    } catch (err) {
      return { status: 0, data: { message: '', status: 'error' }, durationMs: Date.now() - start, message: err instanceof Error ? err.message : String(err) };
    }
  }

  /**
   * 获取历史
   */
  getHistory(): PlatformExportResult[] {
    return [...this.history];
  }

  /**
   * 订阅事件
   */
  subscribe(listener: PlatformEventListener): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  /**
   * 获取端点
   */
  getEndpoint(): PlatformEndpoint {
    return { ...this.config.endpoint };
  }

  /**
   * 获取配置
   */
  getConfig(): GrafanaClientConfig {
    return { ...this.config };
  }

  /**
   * 更新端点
   */
  updateEndpoint(endpoint: PlatformEndpoint): void {
    this.config.endpoint = endpoint;
    this.emit({ type: 'config-updated', platform: this.name, timestamp: Date.now(), data: { endpoint } });
  }

  private emit(event: PlatformEvent): void {
    for (const listener of this.listeners) {
      try { listener(event); } catch { /* ignore */ }
    }
  }
}

/**
 * 创建 Grafana Cloud 端点
 */
export function createGrafanaCloudEndpoint(apiKey: string, region: 'us' | 'eu' | 'asia' = 'us'): PlatformEndpoint {
  const host = region === 'us' ? 'grafana.com' : region === 'eu' ? 'grafana.eu' : 'grafana.cn';
  return {
    name: 'grafana-cloud',
    baseUrl: `https://${host}`,
    protocol: 'https',
    timeoutMs: 15000,
    verifyTls: true,
    credentials: {
      scheme: 'bearer',
      token: apiKey,
    },
  };
}

/**
 * 创建自建 Grafana 端点
 */
export function createSelfHostedGrafanaEndpoint(host: string, port = 3000, credentials?: { username: string; password: string }): PlatformEndpoint {
  return {
    name: 'grafana-self-hosted',
    baseUrl: `http://${host}:${port}`,
    protocol: 'http',
    timeoutMs: 10000,
    verifyTls: false,
    credentials: credentials ? {
      scheme: 'basic',
      username: credentials.username,
      password: credentials.password,
    } : undefined,
  };
}

/**
 * 预置模板：创建默认的 Prometheus + Loki + Tempo Datasource 集
 */
export function createDefaultDatasourceSet(prometheusUrl = 'http://prometheus:9090', lokiUrl = 'http://loki:3100', tempoUrl = 'http://tempo:3200'): GrafanaDatasource[] {
  return [
    {
      name: 'Prometheus',
      type: 'prometheus',
      uid: 'PBFA97CFB590B2093',
      access: 'proxy',
      url: prometheusUrl,
      isDefault: true,
      jsonData: {
        timeInterval: '5s',
        httpMethod: 'POST',
      },
    },
    {
      name: 'Loki',
      type: 'loki',
      uid: 'P8E80F9AEF21F6940',
      access: 'proxy',
      url: lokiUrl,
      jsonData: {
        maxLines: 1000,
      },
    },
    {
      name: 'Tempo',
      type: 'tempo',
      uid: 'PBFA97CFB590B2093',
      access: 'proxy',
      url: tempoUrl,
      jsonData: {
        httpMethod: 'GET',
        serviceMap: { datasourceUid: 'PBFA97CFB590B2093' },
      },
    },
  ];
}
