/**
 * # ============================================================
 * # McpKubernetesPanel - MCP × Kubernetes 配置面板 (Cycle 55 G55-INTEGRATION)
 * # ============================================================
 * # 核心作用：5-Tab UI 集成 K8s Manifest/Helm/CRD/API/文档
 * # Tab 结构：Manifest生成 | Helm Chart | CRD Operator | API客户端 | 集成文档
 * # ====================================
 * # 修改记录：
 * #   - 2026-08-01 | v1.0.0 | Cycle 55 G55-INTEGRATION 初次创建
 * # ====================================
 */

import { useState, useMemo } from 'react';
import {
  buildApplicationStack,
  type ApplicationStackOptions,
} from '../utils/kubernetes/k8sManifestGenerator';
import {
  buildHelmChart,
  packChartFiles,
  type BuildChartOptions,
} from '../utils/kubernetes/helmChartGenerator';
import {
  createMcpAgentCRD,
  createCustomResource,
  buildCRDManifest,
  buildCustomResourceYaml,
  generateRBACManifests,
  McpAgentSpecSchema,
} from '../utils/kubernetes/crdGenerator';
import { K8sApiClient, type K8sAuth } from '../utils/kubernetes/k8sApiClient';

export interface McpKubernetesPanelProps {
  /** 关闭回调 */
  onClose: () => void;
}

/** Tab 标识 */
type TabKey = 'manifest' | 'helm' | 'crd' | 'api' | 'docs';

/** 应用配置 state */
const DEFAULT_STACK: ApplicationStackOptions = {
  name: 'web',
  image: 'nginx:1.25',
  ports: [{ name: 'http', containerPort: 80 }],
  replicas: 3,
  enableHPA: true,
  hpaMin: 2,
  hpaMax: 10,
  enableIngress: true,
  ingressHost: 'web.example.com',
  configMapData: {
    LOG_LEVEL: 'info',
    MAX_CONNECTIONS: '1000',
  },
};

/** API 客户端配置 */
const DEFAULT_API_CONFIG = {
  apiServerUrl: 'https://api.example.com:6443',
  authType: 'bearer' as 'bearer' | 'basic' | 'serviceAccount' | 'anonymous',
  token: '',
  username: '',
  password: '',
  namespace: 'default',
  mode: 'mock' as 'mock' | 'real' | 'hybrid',
};

export default function McpKubernetesPanel({ onClose }: McpKubernetesPanelProps) {
  const [activeTab, setActiveTab] = useState<TabKey>('manifest');
  const [stackOptions, setStackOptions] = useState<ApplicationStackOptions>(DEFAULT_STACK);
  const [apiConfig, setApiConfig] = useState(DEFAULT_API_CONFIG);
  const [apiStatus, setApiStatus] = useState<{
    checking: boolean;
    healthy?: boolean;
    info?: string;
  }>({ checking: false });

  // 计算 manifest 输出
  const manifestYaml = useMemo(() => {
    try {
      const resources = buildApplicationStack(stackOptions);
      const resources_yaml = resources.map((r) => JSON.stringify(r, null, 2)).join('\n---\n');
      return resources_yaml;
    } catch (e) {
      return `# Error: ${e instanceof Error ? e.message : String(e)}`;
    }
  }, [stackOptions]);

  // 计算 Helm chart 输出
  const chartFiles = useMemo(() => {
    try {
      const chartOptions: BuildChartOptions = {
        ...stackOptions,
        chartVersion: '1.0.0',
        chartDescription: `${stackOptions.name} Helm chart generated by MCP × Kubernetes Panel`,
        maintainers: [{ name: 'MCP × Hermes Team', email: 'team@mcp-hermes.io' }],
        keywords: ['mcp', 'hermes', 'kubernetes'],
      };
      const pkg = buildHelmChart(chartOptions);
      return packChartFiles(pkg, stackOptions.name);
    } catch (e) {
      return { error: e instanceof Error ? e.message : String(e) } as unknown as Record<string, string>;
    }
  }, [stackOptions]);

  // CRD 输出
  const crdYaml = useMemo(() => {
    try {
      const crd = createMcpAgentCRD();
      return buildCRDManifest([crd]);
    } catch (e) {
      return `# Error: ${e instanceof Error ? e.message : String(e)}`;
    }
  }, []);

  // CR 实例输出
  const crInstanceYaml = useMemo(() => {
    try {
      const cr = createCustomResource({
        kind: 'McpAgent',
        group: 'mcp.hermes.io',
        version: 'v1',
        name: `${stackOptions.name}-agent`,
        namespace: stackOptions.namespace ?? 'default',
        spec: {
          image: stackOptions.image,
          replicas: stackOptions.replicas ?? 1,
          model: 'claude-sonnet-4.5',
          tools: ['rag-search', 'code-review', 'trace-query'],
          autoscaling: {
            enabled: stackOptions.enableHPA ?? false,
            minReplicas: stackOptions.hpaMin ?? 1,
            maxReplicas: stackOptions.hpaMax ?? 10,
          },
        },
        status: { phase: 'Running', readyReplicas: stackOptions.replicas ?? 1 },
      });
      return buildCustomResourceYaml(cr);
    } catch (e) {
      return `# Error: ${e instanceof Error ? e.message : String(e)}`;
    }
  }, [stackOptions]);

  // RBAC 输出
  const rbacYaml = useMemo(() => {
    try {
      const rbac = generateRBACManifests({
        name: 'mcpagent-controller',
        namespace: 'mcp-system',
        apiGroup: 'mcp.hermes.io',
        resource: 'mcpagents',
        verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete'],
      });
      return [rbac.serviceAccount, rbac.role, rbac.roleBinding]
        .map((r) => JSON.stringify(r, null, 2))
        .join('\n---\n');
    } catch (e) {
      return `# Error: ${e instanceof Error ? e.message : String(e)}`;
    }
  }, []);

  // 测试 API 连接
  const handleTestConnection = async () => {
    setApiStatus({ checking: true });
    try {
      const auth: K8sAuth =
        apiConfig.authType === 'bearer'
          ? { type: 'bearer', token: apiConfig.token }
          : apiConfig.authType === 'basic'
            ? { type: 'basic', username: apiConfig.username, password: apiConfig.password }
            : { type: 'anonymous' };
      const client = new K8sApiClient({
        apiServerUrl: apiConfig.apiServerUrl,
        auth,
        namespace: apiConfig.namespace,
        mode: apiConfig.mode,
        timeoutMs: 10000,
      });
      const result = await client.healthCheck();
      if (result.healthy) {
        const info = await client.getClusterInfo();
        setApiStatus({
          checking: false,
          healthy: true,
          info: `${info.version} | ${info.nodes} nodes | ${info.namespaces} ns | ${info.pods} pods`,
        });
      } else {
        setApiStatus({ checking: false, healthy: false, info: result.error });
      }
    } catch (e) {
      setApiStatus({
        checking: false,
        healthy: false,
        info: e instanceof Error ? e.message : String(e),
      });
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="bg-white dark:bg-gray-900 rounded-lg shadow-2xl w-full max-w-7xl max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 dark:border-gray-700">
          <div>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">
              ☸️ MCP × Kubernetes 配置面板
            </h2>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
              Cycle 55 G55-INTEGRATION | Manifest + Helm + CRD + API 集群编排
            </p>
          </div>
          <button
            onClick={onClose}
            className="px-3 py-1 text-sm bg-gray-100 hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 rounded"
          >
            关闭
          </button>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-gray-200 dark:border-gray-700 px-4 overflow-x-auto">
          {[
            { key: 'manifest', label: '📦 Manifest' },
            { key: 'helm', label: '⎈ Helm Chart' },
            { key: 'crd', label: '🧩 CRD/Operator' },
            { key: 'api', label: '🔌 API 客户端' },
            { key: 'docs', label: '📖 集成文档' },
          ].map((tab) => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key as TabKey)}
              className={`px-4 py-2 text-sm font-medium whitespace-nowrap ${
                activeTab === tab.key
                  ? 'border-b-2 border-blue-500 text-blue-600 dark:text-blue-400'
                  : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {activeTab === 'manifest' && (
            <ManifestTab
              options={stackOptions}
              onChange={setStackOptions}
              yaml={manifestYaml}
            />
          )}
          {activeTab === 'helm' && (
            <HelmTab files={chartFiles} options={stackOptions} onChange={setStackOptions} />
          )}
          {activeTab === 'crd' && (
            <CRDTab crdYaml={crdYaml} crInstanceYaml={crInstanceYaml} rbacYaml={rbacYaml} />
          )}
          {activeTab === 'api' && (
            <APITab
              config={apiConfig}
              onChange={setApiConfig}
              status={apiStatus}
              onTest={handleTestConnection}
            />
          )}
          {activeTab === 'docs' && <DocsTab />}
        </div>
      </div>
    </div>
  );
}

// ============================================================
// Manifest Tab
// ============================================================

interface ManifestTabProps {
  options: ApplicationStackOptions;
  onChange: (opts: ApplicationStackOptions) => void;
  yaml: string;
}

function ManifestTab({ options, onChange, yaml }: ManifestTabProps) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
      {/* 配置面板 */}
      <div className="space-y-3">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">应用配置</h3>

        <div>
          <label className="block text-sm font-medium mb-1">应用名称</label>
          <input
            type="text"
            value={options.name}
            onChange={(e) => onChange({ ...options, name: e.target.value })}
            className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">镜像</label>
          <input
            type="text"
            value={options.image}
            onChange={(e) => onChange({ ...options, image: e.target.value })}
            className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">命名空间</label>
          <input
            type="text"
            value={options.namespace ?? 'default'}
            onChange={(e) => onChange({ ...options, namespace: e.target.value })}
            className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
          />
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="block text-sm font-medium mb-1">副本数</label>
            <input
              type="number"
              value={options.replicas ?? 1}
              min={1}
              onChange={(e) => onChange({ ...options, replicas: Number(e.target.value) })}
              className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
            />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">容器端口</label>
            <input
              type="number"
              value={options.ports[0]?.containerPort ?? 80}
              onChange={(e) =>
                onChange({
                  ...options,
                  ports: [{ name: 'http', containerPort: Number(e.target.value) }],
                })
              }
              className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
            />
          </div>
        </div>

        <div className="border-t border-gray-200 dark:border-gray-700 pt-3">
          <h4 className="text-sm font-semibold mb-2">可选资源</h4>
          <div className="space-y-2">
            <label className="flex items-center">
              <input
                type="checkbox"
                checked={options.enableHPA ?? false}
                onChange={(e) => onChange({ ...options, enableHPA: e.target.checked })}
                className="mr-2"
              />
              <span className="text-sm">启用 HPA 自动伸缩</span>
            </label>
            {options.enableHPA && (
              <div className="grid grid-cols-2 gap-2 pl-6">
                <div>
                  <label className="block text-xs">最小副本</label>
                  <input
                    type="number"
                    value={options.hpaMin ?? 1}
                    onChange={(e) => onChange({ ...options, hpaMin: Number(e.target.value) })}
                    className="w-full px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-sm"
                  />
                </div>
                <div>
                  <label className="block text-xs">最大副本</label>
                  <input
                    type="number"
                    value={options.hpaMax ?? 10}
                    onChange={(e) => onChange({ ...options, hpaMax: Number(e.target.value) })}
                    className="w-full px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-sm"
                  />
                </div>
              </div>
            )}
            <label className="flex items-center">
              <input
                type="checkbox"
                checked={options.enableIngress ?? false}
                onChange={(e) => onChange({ ...options, enableIngress: e.target.checked })}
                className="mr-2"
              />
              <span className="text-sm">启用 Ingress</span>
            </label>
            {options.enableIngress && (
              <div className="pl-6">
                <label className="block text-xs">主机名</label>
                <input
                  type="text"
                  value={options.ingressHost ?? ''}
                  onChange={(e) => onChange({ ...options, ingressHost: e.target.value })}
                  className="w-full px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-sm"
                />
              </div>
            )}
          </div>
        </div>

        <div className="border-t border-gray-200 dark:border-gray-700 pt-3">
          <h4 className="text-sm font-semibold mb-2">资源限制</h4>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <label className="block text-xs">CPU Limit</label>
              <input
                type="text"
                value={options.resources?.cpu?.limit ?? '500m'}
                onChange={(e) =>
                  onChange({
                    ...options,
                    resources: {
                      ...options.resources,
                      cpu: { ...options.resources?.cpu, limit: e.target.value },
                    },
                  })
                }
                className="w-full px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-sm"
              />
            </div>
            <div>
              <label className="block text-xs">Memory Limit</label>
              <input
                type="text"
                value={options.resources?.memory?.limit ?? '512Mi'}
                onChange={(e) =>
                  onChange({
                    ...options,
                    resources: {
                      ...options.resources,
                      memory: { ...options.resources?.memory, limit: e.target.value },
                    },
                  })
                }
                className="w-full px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-sm"
              />
            </div>
          </div>
        </div>
      </div>

      {/* YAML 输出 */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">K8s Manifest YAML</h3>
          <button
            onClick={() => navigator.clipboard?.writeText(yaml)}
            className="px-2 py-1 text-xs bg-blue-500 text-white rounded hover:bg-blue-600"
          >
            复制
          </button>
        </div>
        <pre className="bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded p-3 text-xs overflow-auto h-[500px]">
          {yaml}
        </pre>
      </div>
    </div>
  );
}

// ============================================================
// Helm Tab
// ============================================================

interface HelmTabProps {
  files: Record<string, string>;
  options: ApplicationStackOptions;
  onChange: (opts: ApplicationStackOptions) => void;
}

function HelmTab({ files, options, onChange }: HelmTabProps) {
  const [selectedFile, setSelectedFile] = useState<string>('');
  const fileList = Object.keys(files).sort();
  const currentFile = selectedFile || fileList[0] || '';
  const currentContent = files[currentFile] || '';

  return (
    <div className="grid grid-cols-1 lg:grid-cols-4 gap-4">
      {/* 文件列表 */}
      <div>
        <h3 className="text-sm font-semibold mb-2">Chart 文件 ({fileList.length})</h3>
        <div className="space-y-1 max-h-[500px] overflow-y-auto">
          {fileList.map((f) => (
            <button
              key={f}
              onClick={() => setSelectedFile(f)}
              className={`w-full text-left px-2 py-1 text-xs rounded ${
                currentFile === f
                  ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300'
                  : 'hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-300'
              }`}
            >
              📄 {f}
            </button>
          ))}
        </div>
      </div>

      {/* 文件内容 */}
      <div className="lg:col-span-3">
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-sm font-semibold">{currentFile}</h3>
          <button
            onClick={() => navigator.clipboard?.writeText(currentContent)}
            className="px-2 py-1 text-xs bg-blue-500 text-white rounded hover:bg-blue-600"
          >
            复制
          </button>
        </div>
        <pre className="bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded p-3 text-xs overflow-auto h-[500px]">
          {currentContent}
        </pre>
      </div>
    </div>
  );
}

// ============================================================
// CRD Tab
// ============================================================

interface CRDTabProps {
  crdYaml: string;
  crInstanceYaml: string;
  rbacYaml: string;
}

function CRDTab({ crdYaml, crInstanceYaml, rbacYaml }: CRDTabProps) {
  const [activeDoc, setActiveDoc] = useState<'crd' | 'instance' | 'rbac'>('crd');
  const content = activeDoc === 'crd' ? crdYaml : activeDoc === 'instance' ? crInstanceYaml : rbacYaml;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-4 gap-4">
      {/* 文档选择 + 架构说明 */}
      <div className="space-y-3">
        <div>
          <h3 className="text-sm font-semibold mb-2">CRD 资源</h3>
          <div className="space-y-1">
            <button
              onClick={() => setActiveDoc('crd')}
              className={`w-full text-left px-3 py-2 text-sm rounded ${
                activeDoc === 'crd'
                  ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300'
                  : 'hover:bg-gray-100 dark:hover:bg-gray-800'
              }`}
            >
              🧩 McpAgent CRD
            </button>
            <button
              onClick={() => setActiveDoc('instance')}
              className={`w-full text-left px-3 py-2 text-sm rounded ${
                activeDoc === 'instance'
                  ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300'
                  : 'hover:bg-gray-100 dark:hover:bg-gray-800'
              }`}
            >
              📋 CR 实例
            </button>
            <button
              onClick={() => setActiveDoc('rbac')}
              className={`w-full text-left px-3 py-2 text-sm rounded ${
                activeDoc === 'rbac'
                  ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300'
                  : 'hover:bg-gray-100 dark:hover:bg-gray-800'
              }`}
            >
              🔐 RBAC
            </button>
          </div>
        </div>

        <div className="border-t border-gray-200 dark:border-gray-700 pt-3">
          <h3 className="text-sm font-semibold mb-2">Spec 字段</h3>
          <div className="space-y-1 text-xs">
            {Object.entries(McpAgentSpecSchema.properties ?? {}).map(([key, schema]) => (
              <div key={key} className="flex items-center gap-1">
                <code className="text-xs bg-gray-100 dark:bg-gray-800 px-1 rounded">{key}</code>
                <span className="text-gray-500">({(schema as { type: string }).type})</span>
                {(McpAgentSpecSchema.required ?? []).includes(key) && (
                  <span className="text-red-500 text-xs">*</span>
                )}
              </div>
            ))}
          </div>
        </div>

        <div className="border-t border-gray-200 dark:border-gray-700 pt-3 text-xs text-gray-500">
          <p className="font-semibold mb-1">Kubebuilder 兼容</p>
          <p>本 CRD 遵循 apiextensions.k8s.io/v1 规范，支持 status/scale 子资源、validation 规则、printer columns。</p>
        </div>
      </div>

      {/* YAML 内容 */}
      <div className="lg:col-span-3">
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-sm font-semibold">YAML Manifest</h3>
          <button
            onClick={() => navigator.clipboard?.writeText(content)}
            className="px-2 py-1 text-xs bg-blue-500 text-white rounded hover:bg-blue-600"
          >
            复制
          </button>
        </div>
        <pre className="bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded p-3 text-xs overflow-auto h-[500px]">
          {content}
        </pre>
      </div>
    </div>
  );
}

// ============================================================
// API Tab
// ============================================================

interface APITabProps {
  config: typeof DEFAULT_API_CONFIG;
  onChange: (c: typeof DEFAULT_API_CONFIG) => void;
  status: { checking: boolean; healthy?: boolean; info?: string };
  onTest: () => void;
}

function APITab({ config, onChange, status, onTest }: APITabProps) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
      {/* API 客户端配置 */}
      <div className="space-y-3">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">K8s API 客户端配置</h3>

        <div>
          <label className="block text-sm font-medium mb-1">API Server URL</label>
          <input
            type="text"
            value={config.apiServerUrl}
            onChange={(e) => onChange({ ...config, apiServerUrl: e.target.value })}
            className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
            placeholder="https://api.example.com:6443"
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">命名空间</label>
          <input
            type="text"
            value={config.namespace}
            onChange={(e) => onChange({ ...config, namespace: e.target.value })}
            className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">认证方式</label>
          <select
            value={config.authType}
            onChange={(e) =>
              onChange({ ...config, authType: e.target.value as typeof config.authType })
            }
            className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
          >
            <option value="bearer">Bearer Token</option>
            <option value="basic">Basic Auth</option>
            <option value="anonymous">Anonymous</option>
          </select>
        </div>

        {config.authType === 'bearer' && (
          <div>
            <label className="block text-sm font-medium mb-1">Token</label>
            <input
              type="password"
              value={config.token}
              onChange={(e) => onChange({ ...config, token: e.target.value })}
              className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
              placeholder="eyJhbGciOiJSUzI1NiIs..."
            />
          </div>
        )}

        {config.authType === 'basic' && (
          <div className="grid grid-cols-2 gap-2">
            <div>
              <label className="block text-sm font-medium mb-1">用户名</label>
              <input
                type="text"
                value={config.username}
                onChange={(e) => onChange({ ...config, username: e.target.value })}
                className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">密码</label>
              <input
                type="password"
                value={config.password}
                onChange={(e) => onChange({ ...config, password: e.target.value })}
                className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
              />
            </div>
          </div>
        )}

        <div>
          <label className="block text-sm font-medium mb-1">传输模式</label>
          <select
            value={config.mode}
            onChange={(e) => onChange({ ...config, mode: e.target.value as typeof config.mode })}
            className="w-full px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-800"
          >
            <option value="mock">Mock (开发演示)</option>
            <option value="real">Real (真实集群)</option>
            <option value="hybrid">Hybrid (混合)</option>
          </select>
        </div>

        <button
          onClick={onTest}
          disabled={status.checking}
          className="w-full px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:bg-gray-400 text-sm font-medium"
        >
          {status.checking ? '连接中...' : '测试连接'}
        </button>

        {status.info && (
          <div
            className={`p-3 rounded text-sm ${
              status.healthy
                ? 'bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-300'
                : 'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-300'
            }`}
          >
            <div className="font-semibold mb-1">
              {status.healthy ? '✅ 连接成功' : '❌ 连接失败'}
            </div>
            <div className="text-xs">{status.info}</div>
          </div>
        )}
      </div>

      {/* 功能说明 */}
      <div>
        <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">客户端能力</h3>
        <div className="space-y-2 text-sm">
          <CapabilityItem icon="📋" title="List API" desc="列出 Pods/Deployments/Services/Nodes 等资源" />
          <CapabilityItem icon="🔍" title="Get API" desc="按名称获取单个资源详情" />
          <CapabilityItem icon="➕" title="Create API" desc="创建 Deployment/Service/CustomResource" />
          <CapabilityItem icon="✏️" title="Update API" desc="PUT 完整更新资源" />
          <CapabilityItem icon="🔧" title="Patch API" desc="Strategic/JSON/Merge Patch 部分更新" />
          <CapabilityItem icon="🗑️" title="Delete API" desc="支持 Foreground/Background/Orphan" />
          <CapabilityItem icon="👀" title="Watch API" desc="流式订阅资源变化事件" />
          <CapabilityItem icon="❤️" title="Health Check" desc="通过 /version 端点探测集群健康" />
        </div>

        <div className="mt-4 p-3 bg-blue-50 dark:bg-blue-900/20 rounded text-xs">
          <p className="font-semibold mb-1 text-blue-700 dark:text-blue-300">使用建议</p>
          <p>开发阶段使用 Mock 模式；演示可使用 kind/k3d 本地集群；生产环境对接真实 K8s API Server。</p>
        </div>
      </div>
    </div>
  );
}

function CapabilityItem({ icon, title, desc }: { icon: string; title: string; desc: string }) {
  return (
    <div className="flex items-start gap-2 p-2 border border-gray-200 dark:border-gray-700 rounded">
      <span className="text-lg">{icon}</span>
      <div>
        <div className="font-medium text-gray-900 dark:text-gray-100">{title}</div>
        <div className="text-xs text-gray-500 dark:text-gray-400">{desc}</div>
      </div>
    </div>
  );
}

// ============================================================
// Docs Tab
// ============================================================

function DocsTab() {
  return (
    <div className="space-y-4 text-sm">
      <section>
        <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">
          📖 集成文档
        </h3>
        <p className="text-gray-600 dark:text-gray-400">
          本面板集成 4 个 K8s 核心引擎，演示完整的应用编排到生产部署全流程。
        </p>
      </section>

      <section className="border-t border-gray-200 dark:border-gray-700 pt-4">
        <h4 className="font-semibold mb-2">1️⃣ K8s Manifest 生成器 (G55-01)</h4>
        <p className="text-gray-600 dark:text-gray-400 mb-2">
          声明式构造 9 种 K8s 资源 (Deployment/Service/Ingress/ConfigMap/Secret/HPA/PVC/Namespace/ServiceAccount)，
          自动序列化为标准 YAML。包含自研 YAML 序列化/反序列化器，无外部依赖。
        </p>
        <ul className="list-disc list-inside text-xs text-gray-500 dark:text-gray-400 space-y-1">
          <li>55 个单元测试覆盖所有资源 Builder + round-trip 验证</li>
          <li>支持应用 Stack 一键生成 (ConfigMap + Deployment + Service + HPA + Ingress)</li>
          <li>自动注入 ConfigMap 环境变量</li>
        </ul>
      </section>

      <section className="border-t border-gray-200 dark:border-gray-700 pt-4">
        <h4 className="font-semibold mb-2">2️⃣ Helm Chart 生成器 (G55-02)</h4>
        <p className="text-gray-600 dark:text-gray-400 mb-2">
          生成符合 Helm 3 规范的完整 Chart 包 (Chart.yaml + values.yaml + templates/)。
          6 个标准 templates: deployment/service/serviceaccount/ingress/hpa/NOTES.txt。
        </p>
        <ul className="list-disc list-inside text-xs text-gray-500 dark:text-gray-400 space-y-1">
          <li>32 个测试覆盖所有模板生成逻辑</li>
          <li>标准 _helpers.tpl 辅助函数 (name/fullname/labels/selectorLabels)</li>
          <li>条件渲染支持可选资源 (Ingress/HPA)</li>
        </ul>
      </section>

      <section className="border-t border-gray-200 dark:border-gray-700 pt-4">
        <h4 className="font-semibold mb-2">3️⃣ CRD/Operator SDK (G55-03)</h4>
        <p className="text-gray-600 dark:text-gray-400 mb-2">
          完整 CRD Builder + ControllerManager + 预制 McpAgent CRD schema + RBAC Manifest。
          遵循 apiextensions.k8s.io/v1 + Kubebuilder 规范。
        </p>
        <ul className="list-disc list-inside text-xs text-gray-500 dark:text-gray-400 space-y-1">
          <li>支持 status/scale 子资源 + validation 规则 + printer columns</li>
          <li>ControllerManager: 注册/启动/停止/入队/错误捕获/自动 requeue</li>
          <li>29 个测试覆盖 CRD 构建 + Controller 生命周期</li>
        </ul>
      </section>

      <section className="border-t border-gray-200 dark:border-gray-700 pt-4">
        <h4 className="font-semibold mb-2">4️⃣ K8s API 客户端 (G55-04)</h4>
        <p className="text-gray-600 dark:text-gray-400 mb-2">
          通过 HTTP 与真实 K8s API Server 交互，支持 List/Get/Create/Update/Delete/Patch/Watch。
          4 种认证方式 + mock/real/hybrid 传输模式。
        </p>
        <ul className="list-disc list-inside text-xs text-gray-500 dark:text-gray-400 space-y-1">
          <li>Bearer / Basic / ClientCert / Anonymous 认证</li>
          <li>完整 Watch 流式订阅 (ReadableStream + JSON parser)</li>
          <li>20 个测试含实时事件验证</li>
        </ul>
      </section>

      <section className="border-t border-gray-200 dark:border-gray-700 pt-4">
        <h4 className="font-semibold mb-2">🔗 跨周期集成</h4>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-xs">
          <IntegrationCard
            title="Cycle 51 (部署验证)"
            desc="Health Checker 升级为 K8s Pod livenessProbe 验证"
          />
          <IntegrationCard
            title="Cycle 52 (生产化增强)"
            desc="CanaryDeployment 升级为 K8s 滚动升级 + Argo Rollouts"
          />
          <IntegrationCard
            title="Cycle 53 (可观测性)"
            desc="OTLP/PromQL 升级为 K8s ServiceMonitor + 自动发现"
          />
          <IntegrationCard
            title="Cycle 54 (平台集成)"
            desc="OTLP/Prometheus/Grafana 通过 K8s Operator 部署"
          />
        </div>
      </section>

      <section className="border-t border-gray-200 dark:border-gray-700 pt-4">
        <h4 className="font-semibold mb-2">🚀 实战示例</h4>
        <pre className="bg-gray-50 dark:bg-gray-800 p-3 rounded text-xs overflow-x-auto">
{`# 1. 一键生成应用 Manifest
const stack = buildApplicationStack({
  name: 'web',
  image: 'nginx:1.25',
  ports: [{ containerPort: 80 }],
  enableHPA: true,
  enableIngress: true,
});
const yaml = buildManifestYaml(stack);

# 2. 生成完整 Helm Chart
const chart = buildHelmChart({
  name: 'web',
  image: 'nginx:1.25',
  ports: [{ containerPort: 80 }],
});
const files = packChartFiles(chart, 'web');

# 3. 部署到 K8s
const client = new K8sApiClient({ ... });
for (const r of stack) {
  await client.create(r, { ... });
}

# 4. 监听变化
const stop = await client.watch({
  group: 'apps', version: 'v1', plural: 'deployments',
  onEvent: (e) => console.log(e.type, e.object),
});`}
        </pre>
      </section>
    </div>
  );
}

function IntegrationCard({ title, desc }: { title: string; desc: string }) {
  return (
    <div className="p-2 border border-gray-200 dark:border-gray-700 rounded">
      <div className="font-medium text-gray-900 dark:text-gray-100">{title}</div>
      <div className="text-gray-500 dark:text-gray-400">{desc}</div>
    </div>
  );
}
