/**
 * # ============================================================
 * # Smart Approval Rules - 智能审批内置规则库 (v1.0.0 Cycle 26 G26-02)
 * # ============================================================
 * # 核心作用：提供 40+ 内置安全规则，覆盖 shell/git/file/network/tool
 * # 规则分类：
 * #   1. 安全类（10 条）：禁止危险命令
 * #   2. Git 类（8 条）：Git 操作策略
 * #   3. 文件类（10 条）：文件访问控制
 * #   4. 网络类（8 条）：网络请求控制
 * #   5. 工具类（6 条）：工具调用策略
 * # ============================================================
 * # 修改记录：
 * #   - 2026-07-30 | v1.0.0 | Cycle 26 G26-02 初次创建
 * # ============================================================
 */

import { SmartApprovalRule } from './smartApprovalTypes';

// ============ 安全类规则（10 条） ============

export const BUILTIN_SAFETY_RULES: SmartApprovalRule[] = [
  {
    id: 'builtin-safety-rm-rf',
    name: '禁止 rm -rf',
    description: '禁止递归强制删除命令',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'rm -rf' },
    decision: 'block',
    reason: '禁止递归强制删除命令',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['security', 'dangerous'],
    author: 'system',
  },
  {
    id: 'builtin-safety-sudo',
    name: '禁止 sudo',
    description: '禁止使用 sudo 提权',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'sudo ' },
    decision: 'block',
    reason: '禁止使用 sudo 提权命令',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['security', 'privilege'],
    author: 'system',
  },
  {
    id: 'builtin-safety-chmod-777',
    name: '禁止 chmod 777',
    description: '禁止设置 777 权限',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'chmod 777' },
    decision: 'block',
    reason: '禁止设置全开放权限',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['security', 'permission'],
    author: 'system',
  },
  {
    id: 'builtin-safety-dd',
    name: '禁止 dd 命令',
    description: '禁止使用 dd 直接写设备',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'dd ' },
    decision: 'prompt',
    reason: 'dd 命令可能覆盖磁盘数据',
    priority: 90,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['security', 'dangerous'],
    author: 'system',
  },
  {
    id: 'builtin-safety-mkfs',
    name: '禁止 mkfs 格式化',
    description: '禁止文件系统格式化',
    actionTypes: ['shell'],
    match: { type: 'regex', value: '\\bmkfs\\.' },
    decision: 'block',
    reason: '禁止格式化文件系统',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['security', 'dangerous'],
    author: 'system',
  },
  {
    id: 'builtin-safety-curl-pipe-sh',
    name: '禁止 curl|sh 模式',
    description: '禁止从网络下载并直接执行',
    actionTypes: ['shell'],
    match: {
      all: [
        { type: 'contains', value: 'curl' },
        { type: 'contains', value: '|' },
        { type: 'contains', value: 'sh' },
      ],
    },
    decision: 'block',
    reason: '禁止从网络下载脚本并直接执行',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['security', 'remote-execution'],
    author: 'system',
  },
  {
    id: 'builtin-safety-eval',
    name: '禁止 eval/Function',
    description: '禁止代码动态执行',
    actionTypes: ['shell'],
    match: { type: 'regex', value: '\\b(eval|Function)\\b' },
    decision: 'block',
    reason: '禁止代码动态执行',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['security', 'code-injection'],
    author: 'system',
  },
  {
    id: 'builtin-safety-fork-bomb',
    name: '禁止 fork bomb',
    description: '禁止 fork 炸弹',
    actionTypes: ['shell'],
    match: { type: 'contains', value: ':(){ :|:& };:' },
    decision: 'block',
    reason: '禁止 fork bomb 攻击',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['security', 'dos'],
    author: 'system',
  },
  {
    id: 'builtin-safety-git-force',
    name: '禁止 git push --force',
    description: '禁止强制推送到远程',
    actionTypes: ['shell'],
    match: {
      all: [
        { type: 'contains', value: 'git ' },
        { type: 'contains', value: 'push' },
        { type: 'contains', value: '--force' },
      ],
    },
    decision: 'block',
    reason: '禁止强制推送到远程仓库',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['git', 'safety'],
    author: 'system',
  },
  {
    id: 'builtin-safety-git-reset-hard',
    name: '禁止 git reset --hard',
    description: '禁止硬重置',
    actionTypes: ['shell'],
    match: {
      all: [
        { type: 'contains', value: 'git ' },
        { type: 'contains', value: 'reset' },
        { type: 'contains', value: '--hard' },
      ],
    },
    decision: 'block',
    reason: '禁止硬重置（会丢失未提交修改）',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['git', 'safety'],
    author: 'system',
  },
];

// ============ Git 类规则（8 条） ============

export const BUILTIN_GIT_RULES: SmartApprovalRule[] = [
  {
    id: 'builtin-git-status',
    name: 'Git status 自动放行',
    description: 'git status 是只读操作',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'git status' },
    decision: 'allow',
    reason: 'git status 只读操作',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['git', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-git-log',
    name: 'Git log 自动放行',
    description: 'git log 是只读操作',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'git log' },
    decision: 'allow',
    reason: 'git log 只读操作',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['git', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-git-diff',
    name: 'Git diff 自动放行',
    description: 'git diff 是只读操作',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'git diff' },
    decision: 'allow',
    reason: 'git diff 只读操作',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['git', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-git-add',
    name: 'Git add 自动放行',
    description: 'git add 是暂存操作',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'git add' },
    decision: 'allow',
    reason: 'git add 暂存操作',
    priority: 40,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['git', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-git-commit',
    name: 'Git commit 需确认',
    description: 'git commit 需用户确认',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'git commit' },
    decision: 'prompt',
    reason: 'git commit 需要用户确认',
    priority: 50,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['git', 'confirmation'],
    author: 'system',
  },
  {
    id: 'builtin-git-push',
    name: 'Git push 需确认',
    description: 'git push 需用户确认',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'git push' },
    decision: 'prompt',
    reason: 'git push 需要用户确认',
    priority: 60,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['git', 'confirmation'],
    author: 'system',
  },
  {
    id: 'builtin-git-checkout',
    name: 'Git checkout 需确认',
    description: 'git checkout 需用户确认',
    actionTypes: ['shell'],
    match: { type: 'contains', value: 'git checkout' },
    decision: 'prompt',
    reason: 'git checkout 需要用户确认（可能丢失修改）',
    priority: 60,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['git', 'confirmation'],
    author: 'system',
  },
  {
    id: 'builtin-git-branch-delete',
    name: 'Git branch -D 需确认',
    description: '强制删除分支需确认',
    actionTypes: ['shell'],
    match: {
      all: [
        { type: 'contains', value: 'git ' },
        { type: 'contains', value: 'branch' },
        { type: 'contains', value: '-D' },
      ],
    },
    decision: 'prompt',
    reason: 'git branch -D 强制删除分支',
    priority: 70,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['git', 'confirmation'],
    author: 'system',
  },
];

// ============ 文件类规则（10 条） ============

export const BUILTIN_FILE_RULES: SmartApprovalRule[] = [
  {
    id: 'builtin-file-env-read',
    name: '禁止读取 .env',
    description: '禁止读取环境变量文件',
    actionTypes: ['file:read'],
    match: { type: 'regex', value: '\\.env($|\\.)' },
    decision: 'block',
    reason: '禁止读取 .env 文件（可能包含密钥）',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['file', 'sensitive'],
    author: 'system',
  },
  {
    id: 'builtin-file-env-write',
    name: '禁止写入 .env',
    description: '禁止写入环境变量文件',
    actionTypes: ['file:write'],
    match: { type: 'regex', value: '\\.env($|\\.)' },
    decision: 'block',
    reason: '禁止写入 .env 文件',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['file', 'sensitive'],
    author: 'system',
  },
  {
    id: 'builtin-file-env-delete',
    name: '禁止删除 .env',
    description: '禁止删除环境变量文件',
    actionTypes: ['file:delete'],
    match: { type: 'regex', value: '\\.env($|\\.)' },
    decision: 'block',
    reason: '禁止删除 .env 文件',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['file', 'sensitive'],
    author: 'system',
  },
  {
    id: 'builtin-file-git',
    name: '禁止操作 .git 目录',
    description: '禁止操作 .git 内部文件',
    actionTypes: ['file:read', 'file:write', 'file:delete'],
    match: { type: 'contains', value: '.git/' },
    decision: 'block',
    reason: '禁止直接操作 .git 内部',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['file', 'sensitive'],
    author: 'system',
  },
  {
    id: 'builtin-file-node-modules-write',
    name: '禁止写入 node_modules',
    description: '禁止写入 node_modules',
    actionTypes: ['file:write', 'file:delete'],
    match: { type: 'contains', value: 'node_modules/' },
    decision: 'block',
    reason: '禁止直接修改 node_modules',
    priority: 100,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['file', 'dependency'],
    author: 'system',
  },
  {
    id: 'builtin-file-package-json-read',
    name: 'package.json 读取放行',
    description: '读取 package.json 安全',
    actionTypes: ['file:read'],
    match: { type: 'exact', value: 'package.json' },
    decision: 'allow',
    reason: '读取 package.json 是常见操作',
    priority: 20,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['file', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-file-src-write',
    name: '写入 src/ 需确认',
    description: '写入源代码目录需确认',
    actionTypes: ['file:write'],
    match: { type: 'contains', value: 'src/' },
    decision: 'prompt',
    reason: '写入 src/ 目录需要确认',
    priority: 50,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['file', 'confirmation'],
    author: 'system',
  },
  {
    id: 'builtin-file-tmp-read',
    name: 'tmp 文件放行',
    description: '临时文件操作放行',
    actionTypes: ['file:read', 'file:write', 'file:delete'],
    match: { type: 'contains', value: '/tmp/' },
    decision: 'allow',
    reason: 'tmp 目录操作放行',
    priority: 20,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['file', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-file-lock-read',
    name: 'lock 文件读取放行',
    description: '读取 lock 文件放行',
    actionTypes: ['file:read'],
    match: { type: 'regex', value: '\\.(lock|lock\\.json)$' },
    decision: 'allow',
    reason: 'lock 文件只读',
    priority: 20,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['file', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-file-dist-write',
    name: '写入 dist/ 需确认',
    description: '写入构建产物需确认',
    actionTypes: ['file:write'],
    match: { type: 'contains', value: 'dist/' },
    decision: 'prompt',
    reason: '写入 dist/ 目录需要确认',
    priority: 50,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['file', 'confirmation'],
    author: 'system',
  },
];

// ============ 网络类规则（8 条） ============

export const BUILTIN_NETWORK_RULES: SmartApprovalRule[] = [
  {
    id: 'builtin-net-localhost',
    name: 'localhost 放行',
    description: '本地回环放行',
    actionTypes: ['network', 'api:get', 'api:post', 'api:delete'],
    match: { type: 'regex', value: '(localhost|127\\.0\\.0\\.1)' },
    decision: 'allow',
    reason: '本地回环地址',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['network', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-net-internal',
    name: '内网放行',
    description: '10.x.x.x 段放行',
    actionTypes: ['network', 'api:get', 'api:post', 'api:delete'],
    match: { type: 'regex', value: '\\b10\\.\\d+\\.\\d+\\.\\d+\\b' },
    decision: 'allow',
    reason: '内网 IP',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['network', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-net-github',
    name: 'GitHub API 放行',
    description: '访问 github.com 放行',
    actionTypes: ['network', 'api:get'],
    match: { type: 'contains', value: 'github.com' },
    decision: 'allow',
    reason: 'GitHub 公共 API',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['network', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-net-npm',
    name: 'NPM Registry 放行',
    description: '访问 npm registry 放行',
    actionTypes: ['network', 'api:get'],
    match: { type: 'regex', value: 'registry\\.(npmjs|yarnpkg)\\.com' },
    decision: 'allow',
    reason: 'NPM Registry',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['network', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-net-post-external',
    name: '外部 POST 需确认',
    description: '外部 POST 请求需确认',
    actionTypes: ['api:post'],
    match: {
      all: [
        { not: { type: 'regex', value: '(localhost|127\\.0\\.0\\.1|10\\.|192\\.168\\.)' } },
      ],
    },
    decision: 'prompt',
    reason: '外部 POST 请求需确认',
    priority: 60,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['network', 'confirmation'],
    author: 'system',
  },
  {
    id: 'builtin-net-delete',
    name: 'DELETE 请求需确认',
    description: '所有 DELETE 请求需确认',
    actionTypes: ['api:delete'],
    match: { type: 'prefix', value: '' } as any,
    decision: 'prompt',
    reason: 'DELETE 请求需要确认',
    priority: 60,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['network', 'confirmation'],
    author: 'system',
  },
  {
    id: 'builtin-net-https-default',
    name: '外部网络需确认',
    description: '外部 HTTPS 请求需确认',
    actionTypes: ['network'],
    match: {
      all: [
        { not: { type: 'regex', value: '(localhost|127\\.0\\.0\\.1|10\\.|192\\.168\\.|github\\.com|registry\\.)' } },
        { type: 'regex', value: 'https?://' },
      ],
    },
    decision: 'prompt',
    reason: '外部网络请求需确认',
    priority: 50,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['network', 'confirmation'],
    author: 'system',
  },
  {
    id: 'builtin-net-internal-domain',
    name: '内网域名放行',
    description: '*.internal 域名放行',
    actionTypes: ['network'],
    match: { type: 'regex', value: '\\.internal($|/)' },
    decision: 'allow',
    reason: '内网域名',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['network', 'safe'],
    author: 'system',
  },
];

// ============ 工具类规则（6 条） ============

export const BUILTIN_TOOL_RULES: SmartApprovalRule[] = [
  {
    id: 'builtin-tool-bestofn',
    name: 'BestOfN 调用放行',
    description: 'BestOfN 内部调用放行',
    actionTypes: ['tool'],
    match: { type: 'contains', value: 'bestOfN' },
    decision: 'allow',
    reason: 'BestOfN 内部调用',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['tool', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-tool-subagent',
    name: '子智能体派发放行',
    description: '子智能体派发是核心功能',
    actionTypes: ['subagent'],
    match: { type: 'prefix', value: '' } as any,
    decision: 'allow',
    reason: '子智能体派发',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['tool', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-tool-websearch',
    name: 'Web 搜索放行',
    description: 'Web 搜索是常见操作',
    actionTypes: ['tool', 'network'],
    match: { type: 'contains', value: 'web_search' },
    decision: 'allow',
    reason: 'Web 搜索',
    priority: 30,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['tool', 'safe'],
    author: 'system',
  },
  {
    id: 'builtin-tool-browser',
    name: 'Browser 工具需确认',
    description: '浏览器自动化需确认',
    actionTypes: ['tool'],
    match: { type: 'contains', value: 'browser_' },
    decision: 'prompt',
    reason: '浏览器自动化需要确认',
    priority: 50,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['tool', 'confirmation'],
    author: 'system',
  },
  {
    id: 'builtin-tool-clipboard',
    name: '剪贴板写入需确认',
    description: '写入剪贴板需确认',
    actionTypes: ['tool'],
    match: { type: 'contains', value: 'clipboard_write' },
    decision: 'prompt',
    reason: '剪贴板写入需要确认',
    priority: 50,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['tool', 'confirmation'],
    author: 'system',
  },
  {
    id: 'builtin-tool-fs',
    name: '文件系统访问需确认',
    description: '通用文件系统访问需确认',
    actionTypes: ['tool'],
    match: { type: 'regex', value: '^(file_)?fs_' },
    decision: 'prompt',
    reason: '文件系统访问需要确认',
    priority: 50,
    enabled: true,
    createdAt: 0,
    updatedAt: 0,
    tags: ['tool', 'confirmation'],
    author: 'system',
  },
];

// ============ 合并所有内置规则 ============

export const ALL_BUILTIN_RULES: SmartApprovalRule[] = [
  ...BUILTIN_SAFETY_RULES,
  ...BUILTIN_GIT_RULES,
  ...BUILTIN_FILE_RULES,
  ...BUILTIN_NETWORK_RULES,
  ...BUILTIN_TOOL_RULES,
];

export const TOTAL_BUILTIN_RULES = ALL_BUILTIN_RULES.length;
